# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger: none

parameters:
  - name: debug
    type: boolean
    default: false
    displayName: "Run in debug mode"

resources:
  repositories:
    - repository: obTemplates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

    - repository: CBL-Mariner-Pipelines
      type: git
      name: mariner/CBL-Mariner-Pipelines
      ref: refs/heads/master

    - repository: mariner-parallel-test-system
      type: git
      name: mariner/mariner-parallel-test-system
      ref: refs/heads/mbykhovtsev/tweak-paths # TODO: make sure to use main once finished. Use main branch.

variables:
  - group: "Agent pools (DEV)"
  - group: "Raw toolchain info"
  - name: system.debug
    value: "${{ parameters.debug }}"
  - name: rpmsArtifactNameBase
    value: "RPMs"
  - name: toolchainArtifactNameBase
    value: "Toolchain"
  - name: baseRpmsTarballName
    value: "rpms.tar.gz"
  - name: toolchainRPMsTarballName
    value: "toolchain_built_rpms_all.tar.gz"
  - name: marinerVersion
    value: $[ iif(eq(variables['System.PullRequest.TargetBranch'], 'main'), '2.0', '3.0') ]

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@obTemplates
  parameters:
    featureFlags:
      runOnHost: true
      EnableCDPxPAT: false
    git:
      lfs: false
    globalSdl:
      disableLegacyManifest: true
      policheck:
        break: true
      sbom:
        enabled: false # OB doesn't support Mariner artifacts, so we handle SBOM generation manually.
      tsa:
        enabled: false
    stages:
      - template: ../templates/PackageBuildPRCheck.yml@self
        parameters:
          dailyBuildID: "lkg"
          isDailyBuildUpdateManifests: "false"
          rpmsArtifactNameBase: "$(rpmsArtifactNameBase)"
          toolchainArtifactNameBase: "$(toolchainArtifactNameBase)"
          toolchainRPMsTarballName: "$(toolchainRPMsTarballName)"
          baseRpmsTarballName: "$(baseRpmsTarballName)"

      - template: ../templates/PackageTests.yml@self
        parameters:
          rpmsArtifactNameBase: "$(rpmsArtifactNameBase)"
          toolchainArtifactNameBase: "$(toolchainArtifactNameBase)"
          toolchainRPMsTarballName: "$(toolchainRPMsTarballName)"
          baseRpmsTarballName: "$(baseRpmsTarballName)"
          selfRepoName: self
          marinerVersion: "$(marinerVersion)"
          marinerParallelTestSystemRepoName: mariner-parallel-test-system
          marinerPipelinesRepoName: CBL-Mariner-Pipelines
