# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger: none

parameters:
  - name: debug
    type: boolean
    default: false
    displayName: "Run in debug mode"

resources:
  repositories:
    - repository: obTemplates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

    - repository: CBL-Mariner-Pipelines
      type: git
      name: mariner/CBL-Mariner-Pipelines
      ref: refs/heads/master

    - repository: mariner-parallel-test-system
      type: git
      name: mariner/mariner-parallel-test-system
      ref: refs/heads/mbykhovtsev/tweak-paths # TODO: make sure to use main once finished. Use main branch as default, such as `ref: refs/heads/main`. 

variables:
  - group: "Agent pools (DEV)"
  - group: "Raw toolchain info"
  - name: system.debug
    value: "${{ parameters.debug }}"

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@obTemplates
  parameters:
    featureFlags:
      runOnHost: true
      EnableCDPxPAT: false
    git:
      lfs: false
    globalSdl:
      disableLegacyManifest: true
      policheck:
        break: true
      sbom:
        enabled: false # OB doesn't support Mariner artifacts, so we handle SBOM generation manually.
      tsa:
        enabled: false
    stages:
    - stage: Test
      jobs:
      - job: DevPRCheck
        pool:
          type: linux
        variables:
          ob_artifactBaseName: "foo"
          ob_outputDirectory: $(Build.ArtifactStagingDirectory)
        steps:
        - checkout: CBL-Mariner-Pipelines

        - checkout: mariner-parallel-test-system

        - bash: |
            ls -lart "$(Pipeline.Workspace)"
            ls -lart "$(Build.SourcesDirectory)"
            ls -lart "$(Agent.BuildDirectory)"
      # - template: ../templates/PackageBuildAndTestCheck.yml@self
      #   parameters:
      #     dailyBuildID: "lkg"
      #     rpmsArtifactNameBase: "RPMS"
      #     toolchainArtifactNameBase: "Toolchain"
      #     toolchainRPMsTarballName: "toolchain_built_rpms_all.tar.gz"
      #     baseRpmsTarballName: "rpms.tar.gz"
      #     selfRepoName: self
      #     marinerVersion: $[ iif(eq(variables['System.PullRequest.TargetBranch'], 'main'), '2.0', '3.0') ]
      #     marinerParallelTestSystemRepoName: mariner-parallel-test-system
      #     marinerPipelinesRepoName: CBL-Mariner-Pipelines
