# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger: none

parameters:
  - name: debug
    type: boolean
    default: false
    displayName: "Run in debug mode"

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

    - repository: mariner-parallel-test-system
      type: git
      name: mariner-parallel-test-system
      ref: refs/heads/main

variables:
  - group: "Agent pools (DEV)"
  - group: "Raw toolchain info"
  - name: system.debug
    value: "${{ parameters.debug }}"
  - name: rpmsArtifactNameBase
    value: "RPMs"
  - name: toolchainArtifactNameBase
    value: "Toolchain"
  - name: toolchainTestsArtifactNameBase
    value: "Toolchain_tests"
  - name: baseRpmsTarballName
    value: "rpms.tar.gz"
  - name: toolchainRPMsTarballName
    value: "toolchain_built_rpms_all.tar.gz"

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates
  parameters:
    globalSdl:
      credscan:
        suppressionsFile: .config/CredScanSuppressions.json
    stages:
      - template: ../templates/PackageBuildPRCheck.yml@self
        parameters:
          dailyBuildID: "lkg"
          isDailyBuildUpdateManifests: "false"
          rpmsArtifactNameBase: "$(rpmsArtifactNameBase)"
          toolchainArtifactNameBase: "$(toolchainArtifactNameBase)"
          toolchainTestsArtifactNameBase: "$(toolchainTestsArtifactNameBase)"
          toolchainRPMsTarballName: "$(toolchainRPMsTarballName)"
          baseRpmsTarballName: "$(baseRpmsTarballName)"

      - template: ../templates/PackageTests.yml@self
        parameters:
          rpmsArtifactNameBase: "$(rpmsArtifactNameBase)"
          toolchainArtifactNameBase: "$(toolchainArtifactNameBase)"
          toolchainTestsArtifactNameBase: "$(toolchainTestsArtifactNameBase)"
          toolchainRPMsTarballName: "$(toolchainRPMsTarballName)"
          baseRpmsTarballName: "$(baseRpmsTarballName)"
